### ISSUE TITLE
good project

### ISSUE THREAD

**Issue by bogonain** [Samireltabal/crud-oop-with-membership#1]
hi, thx for this project, i'm loking for user sql table, if you can help :)

**Comment by Samireltabal** [comment]
you are welcome bro , it seems like i forgot to upload the sql file .. here you are  . 
[op.zip](https://github.com/Samireltabal/crud-oop-with-membership/files/1954845/op.zip)

**Comment by bogonain** [comment]
thank you very much, i need it
